-- Nettoyage des données
DELETE FROM Client;
DELETE FROM Demande;
DELETE FROM TypeDevis;
DELETE FROM Devis;
DELETE FROM details_devis;
DELETE FROM Status;
DELETE FROM DemandeStatus;

-- Reset AUTO_INCREMENT
ALTER TABLE Client AUTO_INCREMENT = 1;
ALTER TABLE Demande AUTO_INCREMENT = 1;
ALTER TABLE TypeDevis AUTO_INCREMENT = 1;
ALTER TABLE Devis AUTO_INCREMENT = 1;
ALTER TABLE details_devis AUTO_INCREMENT = 1;
ALTER TABLE Status AUTO_INCREMENT = 1;
ALTER TABLE DemandeStatus AUTO_INCREMENT = 1;

